import Head from 'next/head'
import Image from 'next/image'
import ThemeToggle from '../components/theme-toggle'

const Home: JSX.Element = () => {
  return (
    <div className='py-0 px-8'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-white dark:bg-black min-h-screen py-16 px-0 flex-1 flex flex-col justify-center items-center'>
        <h1 className='m-0 text-7xl text-center'>
          <span>Welcome to </span>
          <a
            href='https://nextjs.org'
            className='hover:underline focus:underline active:underline text-[#0070f3]'
          >
            Next.js!
          </a>
        </h1>

        <p className='my-16 text-base'>
          Get started by editing{' '}
          <code className='bg-[#fafafa] dark:bg-slate-900 rounded text-lg p-3 font-mono'>
            pages/index.tsx
          </code>
        </p>

        <div className='flex items-center justify-center flex-wrap max-w-[800px]'>
          <a
            href='https://nextjs.org/docs'
            className='m-4 p-6 text-left text-inherit rounded-xl border-2 border-solid border-[#eaeaea] max-w-xs hover:border-[#0070f3] hover:text-[#0070f3]'
          >
            <h2 className='my-0 ml-4 mr-0 text-2xl'>Documentation &rarr;</h2>
            <p className='m-0 text-lg'>Find in-depth information about Next.js features and API.</p>
          </a>

          <a
            href='https://nextjs.org/learn'
            className='m-4 p-6 text-left text-inherit rounded-xl border-2 border-solid border-[#eaeaea] max-w-xs hover:border-[#0070f3] hover:text-[#0070f3]'
          >
            <h2 className='my-0 ml-4 mr-0 text-2xl'>Learn &rarr;</h2>
            <p className='m-0 text-lg'>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href='https://github.com/vercel/next.js/tree/canary/examples'
            className='m-4 p-6 text-left text-inherit rounded-xl border-2 border-solid border-[#eaeaea] max-w-xs hover:border-[#0070f3] hover:text-[#0070f3]'
          >
            <h2 className='my-0 ml-4 mr-0 text-2xl'>Examples &rarr;</h2>
            <p className='m-0 text-lg'>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            target='_blank'
            rel='noopener noreferrer'
            className='m-4 p-6 text-left text-inherit rounded-xl border-2 border-solid border-[#eaeaea] max-w-xs hover:border-[#0070f3] hover:text-[#0070f3]'
          >
            <h2 className='my-0 ml-4 mr-0 text-2xl'>Deploy &rarr;</h2>
            <p className='m-0 text-lg'>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className='flex flex-1 py-8 px-0 border-t border-t-solid border-t-[#eaeaea] justify-center items-center'>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
          className='flex justify-center items-center flex-grow'
        >
          Powered by{' '}
          <span className='h-4 ml-2'>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
